name: Automatischer PR-Ersteller

on:
  push:
    branches:
      - IhrBranchName # Hier den Branch angeben, der überwacht werden soll

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      run: |
        hub pr create -b "master" -h "versioning" -m "PR Überschrift" -m "PR Beschreibung"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}