name: Automatischer PR-Ersteller

on:
  push:
    branches:
      - IhrBranchName # Hier den Branch angeben, der überwacht werden soll

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      run: |
        chmod +x create_pr.sh
        ./create_pr.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}