name: Create Pull Request
on:
  push:
    branches:
      - versioning

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: versioning
        title: "Ihre PR-Überschrift"
        body: "Ihre PR-Beschreibung"
        base: "Ziel-Zweig" # Der Zweig, in den die Änderungen gemerged werden sollen