name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
    push:
      branches:
        - feature-1
  
        permissions:
            pull-requests: write
    
    jobs:
        pull-request:
        runs-on: ubuntu-latest
        steps:
                - uses: actions/checkout@v3
                - name: pull-request
                  run: |
                    gh_pr_up() { gh pr create $* || gh pr edit $* }
                    gh_pr_up --title "My pull request" --body "Description"